-- =============================================================================
--  Total ITO · wiki-hub 중앙 DB 스키마 (ORACLE)
--  신규 설치 — 전체 테이블 (01)
--
--  생성 기준 : agents/lib/wikihub_db/models.py (schema_version = 2)
--  생성 방식 : SQLAlchemy 방언 컴파일 — 손으로 고치지 말고 models.py 를 고친 뒤 다시 뽑는다.
--
--  주의. publish.py 는 접속 시 스키마를 자동 생성한다(create_all + 부족한 컬럼 ALTER).
--        이 스크립트는 DBA 검토·사전 생성·권한 분리 운영(발행 계정에 DDL 권한을 주지 않는
--        환경)을 위한 것이다. 둘 중 어느 쪽으로 만들어도 결과는 같다.
-- =============================================================================

-- 빈 DB 에 처음 만들 때 쓴다. 이어서 03_seed_roles.sql 을 실행한다.

-- ---------- wikihub_systems ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_systems ( system_key NVARCHAR2(100) NOT NULL, display_name NVARCHAR2(200) NOT NULL, description NVARCHAR2(1000) DEFAULT '''', owner NVARCHAR2(200) DEFAULT '''', owner_person_id INTEGER, repo_url NVARCHAR2(500) DEFAULT '''', tags NVARCHAR2(500) DEFAULT '''', is_archived SMALLINT NOT NULL, created_at DATE NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (system_key) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_components ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_components ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) NOT NULL, component_type NVARCHAR2(30) NOT NULL, display_name NVARCHAR2(200) DEFAULT '''', repo_root NVARCHAR2(500) DEFAULT '''', stack NVARCHAR2(300) DEFAULT '''', created_at DATE NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_components_key UNIQUE (system_key, component_key) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_pages ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_pages ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) NOT NULL, page_path NVARCHAR2(300) NOT NULL, title NVARCHAR2(300) DEFAULT '''', content CLOB, content_type NVARCHAR2(50) NOT NULL, checksum NVARCHAR2(64) NOT NULL, current_version INTEGER NOT NULL, is_deleted SMALLINT NOT NULL, created_at DATE NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_pages_key UNIQUE (system_key, component_key, page_path) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_pages_scope ON wikihub_pages (system_key, component_key)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_page_versions ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_page_versions ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) NOT NULL, page_path NVARCHAR2(300) NOT NULL, version_no INTEGER NOT NULL, content CLOB, content_type NVARCHAR2(50) NOT NULL, checksum NVARCHAR2(64) NOT NULL, change_type NVARCHAR2(20) NOT NULL, change_summary NVARCHAR2(500) DEFAULT '''', author NVARCHAR2(100) DEFAULT '''', author_person_id INTEGER, created_at DATE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_versions_key UNIQUE (system_key, component_key, page_path, version_no) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_versions_scope ON wikihub_page_versions (system_key, component_key, page_path)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_api_endpoints ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_api_endpoints ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) NOT NULL, method NVARCHAR2(10) DEFAULT '''', path NVARCHAR2(500) DEFAULT '''', norm_path NVARCHAR2(500) DEFAULT '''', handler NVARCHAR2(300) DEFAULT '''', source_file NVARCHAR2(500) DEFAULT '''', auth_required SMALLINT NOT NULL, note NVARCHAR2(500) DEFAULT '''', snapshot_at DATE NOT NULL, PRIMARY KEY (id) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_api_norm_path ON wikihub_api_endpoints (norm_path)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_db_objects ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_db_objects ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) NOT NULL, table_name NVARCHAR2(300) NOT NULL, column_count INTEGER NOT NULL, primary_key NVARCHAR2(500) DEFAULT '''', columns_json CLOB DEFAULT '''', used_by CLOB DEFAULT '''', snapshot_at DATE NOT NULL, PRIMARY KEY (id) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_db_table_name ON wikihub_db_objects (table_name)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_frontend_routes ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_frontend_routes ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) NOT NULL, route_path NVARCHAR2(500) DEFAULT '''', view_name NVARCHAR2(300) DEFAULT '''', source_file NVARCHAR2(500) DEFAULT '''', calls_api CLOB DEFAULT '''', snapshot_at DATE NOT NULL, PRIMARY KEY (id) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_external_links ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_external_links ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) NOT NULL, link_type NVARCHAR2(50) DEFAULT '''', target NVARCHAR2(500) DEFAULT '''', source_file NVARCHAR2(500) DEFAULT '''', line_no NVARCHAR2(20) DEFAULT '''', snapshot_at DATE NOT NULL, PRIMARY KEY (id) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_publish_log ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_publish_log ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) NOT NULL, action NVARCHAR2(50) NOT NULL, pages_total INTEGER NOT NULL, pages_created INTEGER NOT NULL, pages_updated INTEGER NOT NULL, pages_deleted INTEGER NOT NULL, message NVARCHAR2(1000) DEFAULT '''', publisher_person_id INTEGER, created_at DATE NOT NULL, PRIMARY KEY (id) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_content_blobs ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_content_blobs ( checksum NVARCHAR2(64) NOT NULL, algo NVARCHAR2(10) NOT NULL, byte_len INTEGER NOT NULL, data BLOB NOT NULL, PRIMARY KEY (checksum) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_persons ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_persons ( person_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), company NVARCHAR2(100) NOT NULL, department NVARCHAR2(100) DEFAULT '''', employee_no NVARCHAR2(50) NOT NULL, person_name NVARCHAR2(100) NOT NULL, phone NVARCHAR2(50) DEFAULT '''', email NVARCHAR2(200) DEFAULT '''', is_active SMALLINT NOT NULL, created_at DATE NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (person_id), CONSTRAINT uq_persons_company_empno UNIQUE (company, employee_no) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_persons_email ON wikihub_persons (email)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_persons_name ON wikihub_persons (person_name)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_system_owners ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_system_owners ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) DEFAULT '''' NOT NULL, person_id INTEGER NOT NULL, owner_role NVARCHAR2(30) NOT NULL, note NVARCHAR2(300) DEFAULT '''', created_at DATE NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_owner_key UNIQUE (system_key, component_key, person_id, owner_role) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_owner_person ON wikihub_system_owners (person_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_owner_scope ON wikihub_system_owners (system_key, component_key)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_roles ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_roles ( role_code NVARCHAR2(30) NOT NULL, display_name NVARCHAR2(100) NOT NULL, description NVARCHAR2(300) DEFAULT '''', rank INTEGER NOT NULL, is_builtin SMALLINT NOT NULL, created_at DATE NOT NULL, PRIMARY KEY (role_code) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_permissions ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_permissions ( perm_code NVARCHAR2(40) NOT NULL, display_name NVARCHAR2(100) NOT NULL, description NVARCHAR2(300) DEFAULT '''', PRIMARY KEY (perm_code) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_role_permissions ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_role_permissions ( role_code NVARCHAR2(30) NOT NULL, perm_code NVARCHAR2(40) NOT NULL, PRIMARY KEY (role_code, perm_code) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_access_grants ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_access_grants ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), person_id INTEGER NOT NULL, scope_type NVARCHAR2(20) NOT NULL, system_key NVARCHAR2(100) DEFAULT '''' NOT NULL, component_key NVARCHAR2(100) DEFAULT '''' NOT NULL, role_code NVARCHAR2(30) NOT NULL, granted_by_person_id INTEGER, granted_at DATE NOT NULL, expires_at DATE, is_active SMALLINT NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_grant_key UNIQUE (person_id, scope_type, system_key, component_key, role_code) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_grants_person ON wikihub_access_grants (person_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_grants_scope ON wikihub_access_grants (system_key, component_key)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_accounts ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_accounts ( account_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), person_id INTEGER NOT NULL, login_id NVARCHAR2(100) NOT NULL, auth_type NVARCHAR2(20) DEFAULT ''sso'' NOT NULL, password_hash NVARCHAR2(200) DEFAULT '''', last_login_at DATE, is_locked SMALLINT NOT NULL, created_at DATE NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (account_id), CONSTRAINT uq_accounts_login UNIQUE (login_id) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_accounts_person ON wikihub_accounts (person_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_access_log ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_access_log ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), person_id INTEGER, login_id NVARCHAR2(100) DEFAULT '''', action NVARCHAR2(30) NOT NULL, system_key NVARCHAR2(100) DEFAULT '''', component_key NVARCHAR2(100) DEFAULT '''', page_path NVARCHAR2(300) DEFAULT '''', result NVARCHAR2(20) NOT NULL, client_ip NVARCHAR2(50) DEFAULT '''', created_at DATE NOT NULL, PRIMARY KEY (id) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_accesslog_created ON wikihub_access_log (created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_accesslog_person ON wikihub_access_log (person_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_schema_meta ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_schema_meta ( meta_key NVARCHAR2(50) NOT NULL, meta_value NVARCHAR2(200) NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (meta_key) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

