-- =============================================================================
--  Total ITO · wiki-hub 중앙 DB 스키마 (ORACLE)
--  기존 DB 업그레이드 v1 → v2 (02)
--
--  생성 기준 : agents/lib/wikihub_db/models.py (schema_version = 2)
--  생성 방식 : SQLAlchemy 방언 컴파일 — 손으로 고치지 말고 models.py 를 고친 뒤 다시 뽑는다.
--
--  주의. publish.py 는 접속 시 스키마를 자동 생성한다(create_all + 부족한 컬럼 ALTER).
--        이 스크립트는 DBA 검토·사전 생성·권한 분리 운영(발행 계정에 DDL 권한을 주지 않는
--        환경)을 위한 것이다. 둘 중 어느 쪽으로 만들어도 결과는 같다.
-- =============================================================================

-- 이미 운영 중인 wikihub_* DB 에 담당자·권한 표를 더한다.
-- 기존 표의 데이터는 건드리지 않는다. 아래 ALTER 는 전부 NULL 허용 컬럼이라
-- 기존 행에 영향이 없고, 여러 번 실행해도 안전하다.

-- ---------- wikihub_persons ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_persons ( person_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), company NVARCHAR2(100) NOT NULL, department NVARCHAR2(100) DEFAULT '''', employee_no NVARCHAR2(50) NOT NULL, person_name NVARCHAR2(100) NOT NULL, phone NVARCHAR2(50) DEFAULT '''', email NVARCHAR2(200) DEFAULT '''', is_active SMALLINT NOT NULL, created_at DATE NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (person_id), CONSTRAINT uq_persons_company_empno UNIQUE (company, employee_no) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_persons_email ON wikihub_persons (email)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_persons_name ON wikihub_persons (person_name)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_system_owners ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_system_owners ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), system_key NVARCHAR2(100) NOT NULL, component_key NVARCHAR2(100) DEFAULT '''' NOT NULL, person_id INTEGER NOT NULL, owner_role NVARCHAR2(30) NOT NULL, note NVARCHAR2(300) DEFAULT '''', created_at DATE NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_owner_key UNIQUE (system_key, component_key, person_id, owner_role) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_owner_person ON wikihub_system_owners (person_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_owner_scope ON wikihub_system_owners (system_key, component_key)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_roles ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_roles ( role_code NVARCHAR2(30) NOT NULL, display_name NVARCHAR2(100) NOT NULL, description NVARCHAR2(300) DEFAULT '''', rank INTEGER NOT NULL, is_builtin SMALLINT NOT NULL, created_at DATE NOT NULL, PRIMARY KEY (role_code) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_permissions ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_permissions ( perm_code NVARCHAR2(40) NOT NULL, display_name NVARCHAR2(100) NOT NULL, description NVARCHAR2(300) DEFAULT '''', PRIMARY KEY (perm_code) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_role_permissions ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_role_permissions ( role_code NVARCHAR2(30) NOT NULL, perm_code NVARCHAR2(40) NOT NULL, PRIMARY KEY (role_code, perm_code) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_access_grants ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_access_grants ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), person_id INTEGER NOT NULL, scope_type NVARCHAR2(20) NOT NULL, system_key NVARCHAR2(100) DEFAULT '''' NOT NULL, component_key NVARCHAR2(100) DEFAULT '''' NOT NULL, role_code NVARCHAR2(30) NOT NULL, granted_by_person_id INTEGER, granted_at DATE NOT NULL, expires_at DATE, is_active SMALLINT NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_grant_key UNIQUE (person_id, scope_type, system_key, component_key, role_code) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_grants_person ON wikihub_access_grants (person_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_grants_scope ON wikihub_access_grants (system_key, component_key)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_accounts ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_accounts ( account_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), person_id INTEGER NOT NULL, login_id NVARCHAR2(100) NOT NULL, auth_type NVARCHAR2(20) DEFAULT ''sso'' NOT NULL, password_hash NVARCHAR2(200) DEFAULT '''', last_login_at DATE, is_locked SMALLINT NOT NULL, created_at DATE NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (account_id), CONSTRAINT uq_accounts_login UNIQUE (login_id) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_accounts_person ON wikihub_accounts (person_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_access_log ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_access_log ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), person_id INTEGER, login_id NVARCHAR2(100) DEFAULT '''', action NVARCHAR2(30) NOT NULL, system_key NVARCHAR2(100) DEFAULT '''', component_key NVARCHAR2(100) DEFAULT '''', page_path NVARCHAR2(300) DEFAULT '''', result NVARCHAR2(20) NOT NULL, client_ip NVARCHAR2(50) DEFAULT '''', created_at DATE NOT NULL, PRIMARY KEY (id) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_accesslog_created ON wikihub_access_log (created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX ix_accesslog_person ON wikihub_access_log (person_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- wikihub_schema_meta ----------
BEGIN
  EXECUTE IMMEDIATE
    'CREATE TABLE wikihub_schema_meta ( meta_key NVARCHAR2(50) NOT NULL, meta_value NVARCHAR2(200) NOT NULL, updated_at DATE NOT NULL, PRIMARY KEY (meta_key) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ---------- 기존 표에 담당자 연결 컬럼 추가 ----------
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE wikihub_systems ADD (owner_person_id INTEGER NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE wikihub_page_versions ADD (author_person_id INTEGER NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE wikihub_publish_log ADD (publisher_person_id INTEGER NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- 이어서 03_seed_roles.sql 을 실행해 역할·권한 기본값을 채운다.
